config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :projects do
    resources :bugs
  end

  root 'main#home'
  get 'main/home'
  get 'user/:id/bugs', to: 'bugs#user', as: 'user_bugs'
  get 'user/:id/features', to: 'bugs#feature', as: 'user_features'
end

app/models/project.rb
# frozen_string_literal: true

# class Project < ApplicationRecord
class Project < ApplicationRecord
  validates :name, presence: true
  belongs_to :manager, class_name: 'User', foreign_key: 'user_id'

  has_many :bugs, dependent: :destroy

  has_many :user_projects, dependent: :destroy
  has_many :users, through: :user_projects
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# This class ProjectsController < ActionController
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :find_project, only: %i[show edit update destroy]
  before_action :find_users, only: %i[show edit update new]

  def new
    @project = Project.new
  end

  def index
    @projects = Project.where(user_id: current_user.id) if manager?
    @projects = current_user.projects unless manager?
    @projects = @projects.order('updated_at DESC').paginate(page: params[:page], per_page: 4)
  end

  def edit() end

  def create
    # @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      flash[:success] = 'Project created successfully.'
      redirect_to projects_path
    else
      flash[:danger] = 'Project was not created.'
      render 'new', status: :multiple_choices
    end
  end

  def show() end

  def update
    if @project.update(project_params)
      flash[:success] = 'Project updated successfully.'
      redirect_to project_path(@project)
    else
      flash[:danger] = 'Project was not updated.'
      render 'edit', status: :multiple_choices
    end
  end

  def destroy
    if @project.destroy
      flash[:danger] = 'Project deleted successfully.'
      redirect_to projects_path
    else
      render 'show', status: :multiple_choices
    end
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def find_users
    @dev = User.select('id,name').where(user_type: 'Developer')
    @dev.each do |developer|
      developer.name = "Developer - #{developer.name.capitalize}"
    end

    @qa = User.select('id,name').where(user_type: 'QA')
    @qa.each do |q|
      q.name = "QA - #{q.name.capitalize}"
    end

    @user = @dev + @qa
  end

  def project_params
    p = params.require(:project).permit(:name, { users: [] })
    p['users'] = p['users'].reject(&:empty?).map(&:to_i)
    p['users'] = p['users'].map { |id| User.find(id) }
    p
  end
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="field">
    <%= f.label :name, "Name *" %><br />
    <%= f.text_field :name, autofocus: true, required: true %>
  </div>
  <br>

  <div class="field">
    <%= f.label :users, "Assign To:" %>
    <%= f.select :users, options_from_collection_for_select(@user, :id, :name, @project.users.ids), {:include_blank => true},:multiple=> true,:validate=> true,:class=> 'form-control' %> 
  </div>
  <br> 

  <div class="actions">
    <%= f.submit(@project.new_record? ? "Add Project" : "Update Project") %>
  </div>
<% end %>

<br>
<%= link_to "Back", :back %>

app/views/projects/edit.html.erb
<%= render 'shared/page_title', title: "Edit Project" %>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= render 'shared/page_title', title: "Showing All Projects" %>

<br>

<% if @projects.count == 0 %>
    <p>
        No Project <%= "assigned" if !manager? %> yet!
    </p>
<% else %>

<div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero container">
    <ul>
        <li class="disabled"> 
            <%= will_paginate(@projects, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font" ) %>
        </li>
    </ul>
</div>

<ul>
    <% @projects.each do |project| %>
        <li>
            <div class="container-fluid">
                <div>
                    <span class="container">
                        <strong>
                            Project Name:
                        </strong>
                        <em>
                            <%= link_to project.name, project %>
                        </em>
                    </span>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Project Developer's</th>
                            <th>Project QA's</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <ul>
                                    <% project.users.where(user_type: "Developer").each do |dev| %>
                                        <li>
                                            <%= dev.name.capitalize %>
                                        </li>
                                    <% end%>
                                </ul>
                            </td>
                            <td>
                                <ul>
                                    <% project.users.where(user_type: "QA").each do |qa| %>
                                        <li>
                                            <%= qa.name.capitalize %>
                                        </li>
                                    <% end%>
                                </ul>
                            </td>
                            <% if (project.bugs.count != 0) && (project.bugs.find_by(assign_id: current_user.id) || !developer?) && (project.bugs.find_by(created_id: current_user.id) || !qa?) %>
                                <td>
                                    <%= link_to pluralize(project.bugs.count, " bug"), project_bugs_path(project), :project_id => project.id %>
                                </td>
                            <% end %>
                            <% if !developer? %>
                                <td>
                                    <div>
                                        <small>
                                            <%= link_to "Report Bug", new_project_bug_path("", :project_id => project.id) if qa? %>
                                            <%= link_to "Edit this Project", edit_project_path(project) if manager? %> 
                                            <%= link_to ('Delete this project'), project, data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete '#{project.name.capitalize}' project?" }, class: "btn btn-xs" if manager? %>
                                        </small>
                                    </div>
                                </td>
                            <% end %>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="seperator">
                <hr>
            </div>
        </li>
    <% end %>
</ul>

<div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero container">
    <ul class=”pagination”>
        <li class="disabled"> 
            <%= will_paginate(@projects, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font" ) %>
        </li>
    </ul>
</div>

<% end %>

app/views/projects/new.html.erb
<%= render 'shared/page_title', title: "Add New Project" %>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= render 'shared/page_title', title: "Project Details" %>

<br>

<div class="container">
  <h2>
    <span>
        <strong>
            Project Name: 
        </strong>
        <em>
            <%= @project.name %>
        </em>
    </span>
  </h2>
  <br>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Project Developer's</th>
        <th>Project QA's</th>
        <% if !developer? %>
            <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <ul>
                    <% @project.users.where(user_type: "Developer").each do |dev| %>
                        <li>
                            <%= dev.name.capitalize %>
                        </li>
                    <% end%>
                </ul>
            </td>
            <td>
                <ul>
                    <% @project.users.where(user_type: "QA").each do |qa| %>
                        <li>
                            <%= qa.name.capitalize %>
                        </li>
                    <% end%>
                </ul>
            </td>
            <% if !developer? %>
            <td>
                <div>
                    <span>
                        <% if (@project.bugs.count != 0) && (@project.bugs.find_by(assign_id: current_user.id) || !developer?) && (@project.bugs.find_by(created_id: current_user.id) || !qa?) %>
                            <%= link_to pluralize(@project.bugs.count, " bug"), project_bugs_path(@project), :project_id => @project.id %>
                        <% end %>
                    </span>
                    <span>
                        <%= link_to "Edit this Project", edit_project_path(@project) if manager? %>
                    </span>
                    <span>
                        <%= link_to ('Delete this project'), @project, data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete '#{@project.name.capitalize}' project?" }, class: "btn btn-xs" if manager? %>
                    </span>
                    <span>
                        <%= link_to "Report Bug", new_project_bug_path("", :project_id => @project.id) if qa? %>
                    </span>
                </div>
            </td>
            <% end %>
      </tr>
    </tbody>
  </table>
</div>

<br>

<%= link_to "Back to Projects", projects_path %>

<br>