config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :projects do
    resources :bugs
  end

  root 'main#home'
  get 'main/home'
  get 'user/:id/bugs', to: 'bugs#user', as: 'user_bugs'
  get 'user/:id/features', to: 'bugs#feature', as: 'user_features'
end

app/models/bug.rb
# frozen_string_literal: true

# class Bug < ApplicationRecord
class Bug < ApplicationRecord
  mount_uploader :screenshot, AvatarUploader
  # serialize :screenshot, JSON # If you use SQLite, add this line.

  belongs_to :project
  validates :title, presence: true, uniqueness: { scope: :project_id, case_sensitive: false }

  FEATURE_STATUS_OPTIONS = %w(New Started Completed)
  BUG_STATUS_OPTIONS = %w(New Started Resolved)

  validate :custom_validation, on: [:create, :update]
  
  validates :bug_type, presence: true
  belongs_to :solver, class_name: 'User', foreign_key: 'assign_id', dependent: :destroy
  belongs_to :creator, class_name: 'User', foreign_key: 'created_id', dependent: :destroy

  scope :bugs, -> { where(bug_type: 'Bug') }
  scope :features, -> { where(bug_type: 'Feature') }

  def self.m_bugs
    where(bug_type: 'Bug')
  end

  def self.m_features
    where(bug_type: 'Feature')
  end

  private 
  def custom_validation
    if (bug_type == "Bug")
      unless BUG_STATUS_OPTIONS.include?(bug_status)
        flash[:danger] = "Invalid Bug Status."
        render 'bugs/new'
      end
    else
      unless FEATURE_STATUS_OPTIONS.include?(bug_status)
        flash[:danger] = "Invalid Bug Status."
        render 'bugs/new'
      end
    end
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

# This class BugsController < ActionController
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_qa, only: %i[new destroy]
  before_action :authenticate_manager, only: %i[edit update]
  before_action :find_bug, only: %i[show edit update destroy]
  before_action :find_project, only: %i[edit new show index create]
  before_action :find_devs, only: %i[new edit]
  before_action :bug?, only: %i[user feature]

  def new
    @bug = @project.bugs.build
  end

  def index
    @bugs = @project.bugs
    @bugs = @bugs.where(assign_id: current_user.id) if developer?
    @bugs = @bugs.where(created_id: current_user.id) if qa?
    @bugs = @bugs.order('updated_at DESC').paginate(page: params[:page], per_page: 4)
  end

  def edit() end

  def create
    @bug = @project.bugs.build(bug_params)
    @bug.created_id = current_user.id
    if @bug.save
      flash[:success] = 'Bug created successfully.'
      redirect_to project_bug_path(@bug.project,@bug)
    else
      flash[:danger] = 'Bug was not created. Bug Title should be unique.'
      render 'new', status: :multiple_choices
    end
  end

  def show
    @project = @bug.project
  end

  def update
    if @bug.update(bug_params)
      flash[:success] = 'Bug updated successfully.'
      redirect_to project_bug_path(@bug.project)
    else
      flash[:danger] = 'Bug was not updated.'
      render 'edit', status: :multiple_choices
    end
  end

  def destroy
    if @bug.destroy
      flash[:danger] = 'Bug deleted successfully.'
      redirect_to project_bugs_path
    else
      flash[:warning] = 'Bug was not deleted.'
      render 'show', status: :multiple_choices
    end
  end

  def user
    @bugs = find_bugs
    @bugs = @bugs.where(bug_type: 'Bug').paginate(page: params[:page], per_page: 4)
  end

  def feature
    @features = find_bugs
    @features = @features.order('updated_at DESC').where(bug_type: 'Feature').paginate(page: params[:page], per_page: 4)
  end

  private

  def find_bug
    @bug = Bug.find(params[:id])
  end

  def bug_params
    return  params.require(:bug).permit(:bug_status) if developer?

    params.require(:bug).permit(:title, :description, :deadline, :screenshot, :bug_type, :assign_id)
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def find_devs
    @devs = @project.users.where(user_type: 'Developer') # used in view
  end

  def find_bugs
    return @bugs = Bug.where(assign_id: params[:id]) if developer?
    return @bugs = Bug.where(created_id: params[:id]) if qa?
    @bugs = Bug.where(created_id: params[:id])
    @proj = Project.where(user_id: params[:id]) if manager?
    @proj.each do |project|
      @bugs = @bugs + project.bugs
    end
    Bug.where(id: @bugs.map(&:id))
  end

  def authenticate_qa
    unless qa?
      flash[:warning] = 'You are not authorized to access this page.'
      redirect_to project_bugs_path
    end
  end

  def authenticate_manager
    if manager?
      flash[:warning] = 'You are not authorized to access this page.'
      redirect_to project_bugs_path
    end
  end

  def bug?
    @has_bug = Bug.find_by(assign_id: current_user.id)
  end
end

app/views/bugs/_form.html.erb
<%= form_for @bug, url: project_bugs_path do |f| %>
        <% if qa? %>
            <div class="field">
                <%= f.label :title, "Title *" %><br />
                <%= f.text_field :title, autofocus: true %>
            </div>
            <br>

            <div class="field">
                <%= f.label :description, "Description (optional)" %><br />
                <%= f.text_area :description %>
            </div>
            <br>

            <div class="field">
                <%= f.label :deadline, "Set Deadline" %><br />
                <%= f.date_select :deadline %>
            </div>
            <br>

            <div class="field">
                <%= f.label :screenshot, "Add Screenshot (only png gif file accepted)" %><br />
                <%= f.file_field :screenshot %>
            </div>
            <br>

            <div class="field bug_type" id="bug_type" data-controller="bug">
                <%= f.label :bug_type, "Bug Type *" %><br />
                <%= f.select :bug_type, ['Feature','Bug'] %>
            </div>
            <br>
        <% end %>

        <% if developer? %>
            <div class="field bug_status" id="bug_status" data-controller="bug">
                <%= f.label :bug_status, "#{@bug.bug_type} Status *" %><br />
                <% if @bug.bug_type == "Feature" %>
                    <%= f.select :bug_status, ['New','Started', 'Completed'] %>
                <% else %>
                    <%= f.select :bug_status, ['New','Started', 'Resolved'] %>
                <% end %>
            </div>
            <br>
        <% end %>

        <% if @bug.new_record? && !@devs.nil? %>
            <div class="field">
                <%= f.label :assign_id, "Assign To:" %><br />
                <%= f.collection_select :assign_id, @devs, :id, :name do |cs| %>
                    <%= cs.label :name %>
                <% end %>
            </div>
            <br>
        <% end %>
        <br>
        <div class="actions">
            <%= f.submit(@bug.new_record? ? "Create Bug" : "Update Bug") %>
        </div>

    <% end %>

<br>
<%= link_to "Back to Bugs listing", project_bugs_path(@bug.project) %>

app/views/bugs/_list.html.erb
<br>

<% if objs.count == 0 %>
    <p>
        No Feature <%= "created" if !qa? %> yet!
    </p>
<% else %>
    <ul>
        <div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero container">
            <ul class=”pagination”>
                <li class="disabled"> 
                    <%= will_paginate(objs, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font justify-content-center" ) %>
                </li>
            </ul>
        </div>
        <% objs.each do |obj| %>
        <li>
            <div class="container">
                <div>
                    <span class="container">
                        <h6>
                            <%= obj.bug_type.capitalize %> Title:
                        </h6>
                        <em>
                            <%= link_to obj.title.capitalize, project_bug_path(obj.project,obj) %>
                        </em>
                    </span>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th>Deadline</th>
                            <th>Status</th>
                            <th>Project Name</th>
                            <th>Project Developer's</th>
                            <th>Project QA's</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <%= truncate(obj.description, length: 150) %>
                            </td>
                            <td>
                                <%= obj.deadline %>
                            </td>
                            <td>
                                <%= obj.bug_status %>
                            </td>
                            <td>
                                <%= link_to obj.project.name.capitalize, obj.project %>
                            </td>
                            <td>
                                <ul>
                                    <% obj.project.users.where(user_type: "Developer").each do |dev| %>
                                        <li>
                                            <%= dev.name.capitalize %>
                                        </li>
                                    <% end%>
                                </ul>
                            </td>
                            <td>
                                <ul>
                                    <% obj.project.users.where(user_type: "QA").each do |qa| %>
                                        <li>
                                            <%= qa.name.capitalize %>
                                        </li>
                                    <% end%>
                                </ul>
                            </td>

                            <% if (@has_bug || !developer?) %>
                                <td>
                                    <%#= link_to pluralize(Project.find(obj.project.id).bugs.count, "bug and feature"), project_bugs_path(obj.project), :project_id => obj.project.id %>
                                    <%= link_to pluralize(obj.project.bugs.where(assign_id: current_user.id).count, " Bug/Feature"), project_bugs_path(obj.project), :project_id => obj.project.id if developer? %>
                                    <%= link_to pluralize(obj.project.bugs.where(created_id: current_user.id).count, " Bug/Feature"), project_bugs_path(obj.project), :project_id => obj.project.id if qa? %>
                                    <%= link_to pluralize(obj.project.bugs.count, " Bug/Feature"), project_bugs_path(obj.project), :project_id => obj.project.id if manager? %>
                                </td>
                            <% end %>

                            <% if false && manager? %>
                                <td>
                                    <div>
                                        <small>
                                            <%= link_to "Edit this Project", edit_project_path(obj.project) if manager? %> 
                                            <%= link_to ('Delete this project'), obj.project, data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete '#{obj.project.name.capitalize}' project?" }, class: "btn btn-xs" if manager? %>
                                        </small>
                                    </div>
                                </td>
                            <% end %>

                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="seperator">
                <br>
            </div>
                        
        </li>
        <% end %>
        <div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero container">
            <ul class=”pagination”>
                <li class="disabled"> 
                    <%= will_paginate(objs, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font justify-content-center" ) %>
                </li>
            </ul>
        </div>
    </ul>
<% end %>

app/views/bugs/edit.html.erb
<%= render 'shared/page_title', title: "Edit Bug | Project: #{@project.name.capitalize}" if !@project.nil? %>

<%= form_for(@bug, url: project_bug_path(@bug), :method => "put" ) do |f| %>
    <% if qa? %>
        <div class="field">
            <%= f.label :title, "Title *" %><br />
            <%= f.text_field :title, autofocus: true %>
        </div>
        <br>
        <div class="field">
            <%= f.label :description, "Description (optional)" %><br />
            <%= f.text_area :description %>
        </div>
        <br>
        <div class="field">
            <%= f.label :deadline, "Set Deadline" %><br />
            <%= f.date_select :deadline %>
        </div>
        <br>
        <div class="field">
            <%= f.label :screenshot, "Add Screenshot (only png gif file accepted)" %><br />
            <%= f.file_field :screenshot %>
        </div>
        <br>
        <div class="field bug_type" id="bug_type" data-controller="bug">
            <%= f.label :bug_type, "Bug Type *" %><br />
            <%= f.select :bug_type, ['Feature','Bug'] %>
        </div>
        <br>
    <% end %>

    <% if developer? %>
        <div class="field bug_status" id="bug_status" data-controller="bug">
            <%= f.label :bug_status, "#{@bug.bug_type} Status *" %><br />
            <% if @bug.bug_type == "Feature" %>
                <%= f.select :bug_status, ['New','Started', 'Completed'] %>
            <% else %>
                <%= f.select :bug_status, ['New','Started', 'Resolved'] %>
            <% end %>
        </div>
        <br>
    <% end %>

    <% if @bug.new_record? && !@devs.nil? %>
        <div class="field">
            <%= f.label :assign_id, "Assign To:" %><br />
            <%= f.collection_select :assign_id, @devs, :id, :name do |cs| %>
                <%= cs.label :name %>
            <% end %>
        </div>
        <br>
    <% end %>
    <br>
    <div class="actions">
        <%= f.submit "Updated Bug" %>
    </div>

<% end %>

<br>
<%= link_to "Back to Bugs listing", project_bugs_path(@bug.project) %>

app/views/bugs/feature.html.erb
<%= render 'shared/page_title', title: "Listing All #{pluralize(@features.count, "Feature")}" %>

<%= render 'bugs/list', objs: @features %>

app/views/bugs/index.html.erb
<%= render 'shared/page_title', title: "Showing All Bug/Feature | Project Title: #{@project.name} " %>

<ul>
    <hr/>
    <br>
    <div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero container">
        <ul class=”pagination”>
            <li class="disabled"> 
                <%= will_paginate(@bug, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font" ) %>
            </li>
        </ul>
    </div>

    <% @bugs.each do |bug| %>
        <li>
            <div>
                <span>
                    <strong>
                        Bug Title: 
                    </strong>
                    <span>
                        <%= bug.title %>
                    </span>
                </span>
            </div>
            <br>
            <div>
                <span>
                    <strong>
                        Description: 
                    </strong>
                    <span>
                        <%= truncate(bug.description, length: 150) %>
                    </span>
                </span>
            </div>
            <br>
            <div>
                <span>
                    <strong>
                        Deadline: 
                    </strong>
                    <span>
                        <%= bug.deadline %>
                    </span>
                </span>
            </div>
            <br>
            <% if bug.screenshot? %>
                <div>
                    <span>
                        <strong>
                            Screen Shot: 
                        </strong>
                        <div>
                            <%= image_tag bug.screenshot.url if bug.screenshot? %>
                        </div>
                    </span>
                </div>
                <br>
            <% end %>
            <div>
                <span>
                    <strong>
                        Bug Type: 
                    </strong>
                    <span>
                        <%= bug.bug_type %>
                    </span>
                </span>
            </div>
            <% if !developer? && !bug.assign_id.nil? %>
                <br>
                <div>
                    <span>
                        <strong>
                            Assigned To: 
                        </strong>
                        <span>
                            <%= User.find_by_id(bug.assign_id).name.capitalize %>
                        </span>
                    </span>
                </div>
            <% end %>
            <br>
            <div>
                <span>
                    <strong>
                        Status: 
                    </strong>
                    <span>
                        <%= bug.bug_status %>
                    </span>
                </span>
            </div>
            <% if !qa? %>
                <br>
                <div>
                    <span>
                        <strong>
                            Created By: 
                        </strong>
                        <span>
                            <%= User.find_by_id(bug.created_id).name.capitalize %>
                        </span>
                    </span>
                </div>
            <% end %>

            <div align="right">
                <%#= link_to "Edit this Bug", "/projects/#{@project.id}/bugs/#{bug.id}/edit" if !manager? %>
                <%#= link_to ('Remove this Bug'), "/projects/#{@project.id}/bugs/#{bug.id}", data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this bug?" }, class: "btn btn-xs" if qa? %>
                <%= link_to "Edit this Bug", edit_project_bug_path(@project,bug) if !manager? %>
                <%= link_to ('Remove this Bug'), project_bug_path(@project,bug), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this bug?" }, class: "btn btn-xs" if qa? %>
            </div>
        <hr/>
    </li>
    <% end %>

    <div class="col-lg-8 col-md-8 col-sm-7 col-xs-6 padding-zero">
        <ul class=”pagination”>
            <li class="disabled"> 
                <%= will_paginate(@bugs, previous_label: "&laquo;", next_label: "&raquo;", outer_window: 1, inner_window: 0, class: "small-font" ) %>
            </li>
        </ul>
    </div>

</ul>

app/views/bugs/new.html.erb
<%= render 'shared/page_title', title: "Create Bug | Project: #{@project.name.capitalize}" %>

<%= render 'form' %>

app/views/bugs/show.html.erb
<%= render 'shared/page_title', title: "#{ @bug.bug_type == "Bug" ? "Bug" : "Feature"} Details |  Project Title:  #{@project.name.capitalize}" %>

<div>
    <div>
        <span>
            <em>
                Bug Title: 
            </em>
            <strong>
                <%= @bug.title.capitalize %>
            </strong>
        </span>
    </div>
    <div>
        <span>
            <em>
                Description: 
            </em>
            <h6>
                <%= truncate(@bug.description, length: 150) %>
            </h6>
        </span>
    </div>
    <div>
        <span>
            <em>
                Deadline: 
            </em>
            <h6>
                <%= @bug.deadline %>
            </h6>
        </span>
    </div>
    <div>
        <% if @bug.screenshot? %>
            <em>
                Screen Shot: 
            </em>
            <div>
                <%= image_tag @bug.screenshot.url  if @bug.screenshot? %>
            </div>
        <% end %>
    </div>
    <div>
        <span>
            <em>
                Bug Type: 
            </em>
            <h6>
                <%= @bug.bug_type %>
            </h6>
        </span>
    </div>

    <% if !developer? %>
        <div>
            <span>
                <em>
                    Assigned To: 
                </em>
                <h6>
                    <%= User.find(@bug.assign_id).name %>
                </h6>
            </span>
        </div>
    <% end %>

    <div>
        <span>
            <em>
                Status: 
            </em>
            <h6>
                <%= @bug.bug_status %>
            </h6>
        </span>
    </div>

    <% if !qa? %>
        <div>
            <span>
                <em>
                    Created By: 
                </em>
                <h6>
                    <%= User.find(@bug.created_id).name.capitalize %>
                </h6>
            </span>
        </div>
    <% end %>

    <%= link_to "Edit this Bug", edit_project_bug_path(@bug.project), :project_id => @project.id  if !manager? %>
    <%= link_to ('Remove this Bug'), project_bug_path(@bug.project), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this bug?" }, class: "btn btn-xs" if qa? %>
    <hr>
    <%= link_to "Back to Bugs listing", project_bugs_path(@bug.project) %>
</div>

app/views/bugs/user.html.erb
<%= render 'shared/page_title', title: "Listing All #{pluralize(@bugs.count, "Bug")}" %>

<%= render 'bugs/list', objs: @bugs %>