config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :projects do
    resources :bugs
  end

  root 'main#home'
  get 'main/home'
  get 'user/:id/bugs', to: 'bugs#user', as: 'user_bugs'
  get 'user/:id/features', to: 'bugs#feature', as: 'user_features'
end

app/views/layouts/_footer.html.erb
<br>

<div class="container">
    <div class="row" id="news-letter">
        <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5>Subscribe to our newsletter</h5>
          <p>Monthly digest of what's new and exciting from us.</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-primary" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>
  <footer class="py-3 my-4 container">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
    </ul>
    <p class="text-center text-body-secondary">&copy; 2023 VisNext, Software Solution - Powered by: Saif</p>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div claas="col-md-10 col-md-offset-1">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name %>" >
                <a href="#" class="close" data-dismiss="alert" >
                    &#215;
                </a>
                <%= msg %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="https://www.visnext.com/assets/green/logo-ad952d6639a40b13cdce727dc91d3e9a73beac31ac87681319ddbb139e82bca2.svg" alt="Visnext Software Solutions Logo" width="60" height="40">
    </a>
    <a class="navbar-brand" href="/">Advance-Bug-Tracking-System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to "Project", projects_path %>
            <%# <a class="nav-link" href="#">Project</a> %>
          </li>
          <% if manager? %>
            <li class="nav-item">
              <%= link_to "New Project", new_project_path %>
            </li>
          <% end %>
          <% if !current_user.projects.nil? %>
            <li class="nav-item">
              <%= link_to "Bugs", "/user/#{current_user.id}/bugs" %>
              <%#= link_to "Bugs", project_bugs_path(Project.find_by(user_id: current_user)) %>
            </li>
            <li class="nav-item">
              <%= link_to "Features", "/user/#{current_user.id}/features" %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"><strong></u><%= current_user.name %>'s Dashboard</strong></li>
          <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_slide.html.erb
<div class="container my-5">
  <div class="position-relative p-5 text-center text-muted bg-body border border-dashed rounded-5">
    <button type="button" class="position-absolute top-0 end-0 p-3 m-3 btn-close bg-secondary bg-opacity-10 rounded-pill" aria-label="Close"></button>
    <a class="navbar-brand" href="/">
        <img src="https://www.visnext.com/assets/green/logo-ad952d6639a40b13cdce727dc91d3e9a73beac31ac87681319ddbb139e82bca2.svg" alt="Visnext Software Solutions Logo">
    </a>
    <%# <svg class="bi mt-5 mb-3" width="48" height="48"><use xlink:href="#check2-circle"/></svg> %>
    <h1 class="text-body-emphasis">
        Ship great software with automated
    </h1>
    <h1 class="text-body-emphasis">
        bug-tracking!
    </h1>
    <p class="col-lg-6 mx-auto mb-4">
        A simple, fast and scalable bug tracking system that helps you manage bugs easily and deliver great products on time.    </p>
        <a href="/users/sign_up" class="button btn btn-primary px-5 mb-5">  Sign Up for free!</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Advance_Bug_Tracking_System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/navbar' %>
    <div class="container center">
      <%= yield %>
    </div>
    <%= render 'layouts/slide' if current_user.nil? %>
    <%= render 'layouts/footer' %>    
  </body>
</html>